apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-cluster
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/demo-app/overlays/prod
  sourceRef:
    kind: GitRepository
    name: eks-gitops
  prune: true
  targetNamespace: prod

