apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-cluster
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-gitops

